# Generated by Django 5.0.1 on 2025-08-05 15:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimationSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField()),
                ("total_duration", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GestureLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("contextual", "Contextual"),
                            ("emotional", "Emotional"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("animation_data", models.JSONField()),
                ("duration", models.FloatField(help_text="Duration in seconds")),
                ("trigger_keywords", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnimationFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("intensity", models.FloatField(default=1.0)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animation.animationsequence",
                    ),
                ),
                (
                    "gesture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animation.gesturelibrary",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="animationsequence",
            name="gestures",
            field=models.ManyToManyField(
                through="animation.AnimationFrame", to="animation.gesturelibrary"
            ),
        ),
    ]
