# Generated by Django 5.0.1 on 2025-08-05 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvatarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "avatar_type",
                    models.CharField(
                        choices=[
                            ("vrm", "VRM Model"),
                            ("ready_player_me", "Ready Player Me"),
                            ("mixamo", "Mixamo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_file", models.FileField(upload_to="avatars/models/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/thumbnails/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AvatarState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField()),
                (
                    "current_emotion",
                    models.CharField(
                        choices=[
                            ("neutral", "Neutral"),
                            ("happy", "Happy"),
                            ("concerned", "Concerned"),
                            ("empathetic", "Empathetic"),
                            ("thinking", "Thinking"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("is_speaking", models.BooleanField(default=False)),
                ("current_gesture", models.CharField(blank=True, max_length=50)),
                ("lip_sync_data", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
